name: Go CD Pipeline

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  docker-host-deploy:
    name: Deploy to Google Cloud Run
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="image_tag=latest"

    # do docker login if the iamge is in private repo

    
      - name: Deploy Docker container on VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}   
          password: ${{ secrets.SSH_PASSWORD }} 
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo docker pull docker.io/mohanreddy/testBuild-v2:latest
            sudo docker run -d --name go-app -p 80:8080 docker.io/mohanreddy/testBuild-v2:latest