name: Go CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: mohanreddy819/gha-pipelines/.github/workflows/ci-reusable.yaml@main
    with:
      projectName: "my-go-service"
      checkoutCode: true
      goVersion: "1.21"
      cacheRequired: true
      preBuildCommand: "echo Pre-build steps here"
      buildCommand: "go build ./..."
      testCommand: "go test ./..." 
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Set up Go
    #     uses: actions/setup-go@v5
    #     with:
    #       go-version: '1.21'



      # - name: Build
      #   run: go build -v ./...
  docker-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mohanreddy819/testBuild-v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
