name: Go CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'

            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                path: |
                     ~/.cache/go-build
                     ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                    ${{ runner.os }}-go-

            - name: Build
              run: go build -v ./...

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract Docker image metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: mohanreddy819/testBuild
            - name: pushing the image into the docker
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}